server:
  port: 8800
spring:
  application:
    name: consul-provider-demo
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}