server:
  port: 8082
spring:
  application:
    name: provider-demo-service

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: true
    service-url:
      #集群
      defaultZone: http://eurekaServerDemo01.com:7001/eureka/,http://eurekaServerDemo02.com:7002/eureka/