server:
  port: 6001
spring:
  application:
    name: hystrix-learn-provider

eureka:
  client:
    service-url:
      #集群
      defaultZone: http://eurekaServerDemo01.com:7001/eureka/,http://eurekaServerDemo02.com:7002/eureka/