server:
  port: 7002
spring:
  application:
    name: eureka-server-demo-02

eureka:
  instance:
    #eureka服务端实例名称
    hostname: eurekaServerDemo02.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置eureka server交互的地址：查询服务和注册服务都需要依赖这个地址（两个注册中心相互守望）
      defaultZone: http://eurekaServerDemo01.com:7001/eureka/
